# SPDX-License-Identifier: GPL-2.0-only
ccflags-y += -I$(src)

obj-$(CONFIG_SAMPLE_HCK_CALL)			+= call.o
obj-$(CONFIG_SAMPLE_HCK_REGISTER)		+= register.o
obj-$(CONFIG_SAMPLE_HCK_REGISTER_ONE)	+= register_one.o